### ISSUE TITLE
作者竟然是国人!点赞！

### ISSUE THREAD

**Issue by freeboss12** [sheilaCat/zknotes#1]
最近在折腾卡片式写作的相关软件，没有一个尽如人意的，突发奇想，vsc能写markdown，应该也有人开发卡片式写作的插件吧？插件市场里一搜，竟然有好几个，比一比哪个好的过程中，竟然发现您是国人，专门过来留言。另外，一点点小小的提示，可视化功能不需要单独开发了，因为我在市场里面找到了一款叫md-graph的插件，可以直接完成可视化。支持您继续完善这款插件！

**Comment by sheilaCat** [comment]
一开始这款插件就建立在兼容`markdown-links`的基础上，新增页面时会自动添加对应的一级标题。

（另外，其实md-graph也是markdown-links的fork）

今天更新了插件，把`markdown-links`集成进来了，但后续希望在界面上会更靠近一些神经网络的软件。

后续也会支持诸如`back-links`之类的反向链接，如有别的建议可以新增issue，感谢喜欢！

---

This plugin is based on the compatibility with `markdown-links`, and it will automatically add the corresponding level 1 title when adding a new page.

(actually md-graph is one fork of markdown-links)

Today I updated the plugin to integrate `markdown-links`, but I hope the interface will be closer to some neural network software.

We'll also support backlinks , and if you have any other suggestions you can create new issue, thanks!
